### ISSUE TITLE
Failed to run the graph

### ISSUE THREAD

**Issue by TyrusRC** [thanhsang298/Viet-Nam-Sign-Language-Recognition-using-Hand-MediaPipe-framework-and-LSTM-model#1]
when i try to convert video to txt file,  could you help me fix this issues :

# Subgraph that renders annotations and overlays them on top of the input
# images (see multi_hand_renderer_cpu.pbtxt).
node {
  calculator: "MultiHandRendererSubgraph"
  input_stream: "IMAGE:input_video"
  input_stream: "DETECTIONS:multi_palm_detections"
  input_stream: "LANDMARKS:multi_hand_landmarks"
  input_stream: "NORM_RECTS:0:multi_palm_rects"
  input_stream: "NORM_RECTS:1:multi_hand_rects"
  output_stream: "IMAGE:output_video"
}
I20201018 09:17:33.736898 11864 demo_run_graph_main.cc:62] Initialize the calculator graph.
I20201018 09:17:33.739692 11864 demo_run_graph_main.cc:66] Initialize the camera or load the video.
E20201018 09:17:33.743739 11864 demo_run_graph_main.cc:163] Failed to run the graph: ;

**Comment by thanhsang298** [comment]
> when i try to convert video to txt file, could you help me fix this issues :
> 
> # Subgraph that renders annotations and overlays them on top of the input
> # images (see multi_hand_renderer_cpu.pbtxt).
> node {
> calculator: "MultiHandRendererSubgraph"
> input_stream: "IMAGE:input_video"
> input_stream: "DETECTIONS:multi_palm_detections"
> input_stream: "LANDMARKS:multi_hand_landmarks"
> input_stream: "NORM_RECTS:0:multi_palm_rects"
> input_stream: "NORM_RECTS:1:multi_hand_rects"
> output_stream: "IMAGE:output_video"
> }
> I20201018 09:17:33.736898 11864 demo_run_graph_main.cc:62] Initialize the calculator graph.
> I20201018 09:17:33.739692 11864 demo_run_graph_main.cc:66] Initialize the camera or load the video.
> E20201018 09:17:33.743739 11864 demo_run_graph_main.cc:163] Failed to run the graph: ;

Hi @Trumpiter-max , you musst chance threes files in "modified_mediapipe" folder like this image below
![image](https://user-images.githubusercontent.com/51918703/96358477-c7515d00-1131-11eb-834b-afe976524625.png) 
and set up Mediapipe framework in step 1

**Comment by TyrusRC** [comment]
Thanks, but I did that, just replace files and build it again, right ?

**Comment by thanhsang298** [comment]
> Thanks, but I did that, just replace files and build it again, right ?

Could you capture your project folder screen?

**Comment by thanhsang298** [comment]
> Thanks, but I did that, just replace files and build it again, right ?

Right. You just replace files after installing framework and build it again. After that, you can tell me the result.

**Comment by TyrusRC** [comment]
![image](https://user-images.githubusercontent.com/63230297/96367069-d22de100-1175-11eb-9666-8a58038b287f.png)
Here, after i build it again, it seems not recognoize the mediapipe.

**Comment by TyrusRC** [comment]
![image](https://user-images.githubusercontent.com/63230297/96367227-b119c000-1176-11eb-8750-da179826997c.png)
Is it installed sucessfully, right ?, or i need to do something else.

**Comment by TyrusRC** [comment]
![image](https://user-images.githubusercontent.com/63230297/96405239-056c8080-1207-11eb-8cf6-d220793d99cd.png)

**Comment by thanhsang298** [comment]
After installing Mediapipe, you must build Hands Mediapipe in Command line: 
![image](https://user-images.githubusercontent.com/51918703/96817806-4f917400-144a-11eb-81a5-84a125a81e0d.png)
[link in here](https://google.github.io/mediapipe/solutions/hands.html)
Then, you access your mediapipe folder (mediapipe/mediapipe/....) to copy it and paste into your project folder and build it again

**Comment by TyrusRC** [comment]
Thanks a lot, i will try, this session would be closed now.
